### ISSUE TITLE
logging from within the ReconcileFunc?

### ISSUE THREAD

**Issue by rosenhouse** [imikushin/controllers-af#2]
Hi, I'm trying out this library for the first time.

What's a good way to get a logger from within the Reconcile callback?

Could I pull one off the context somehow (first function argument)?

**Comment by imikushin** [comment]
I'd say, the best way is probably to have the logger as a field in a struct, and have the ReconcileFunc to be a method of the struct. Something along the lines of:

```go
type ConfigMapCountReconciler struct {
	Log logr.Logger
}

func (r *ConfigMapCountReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&sillyv1alpha1.ConfigMapCount{}).
		Watches(&source.Kind{Type: &corev1.ConfigMap{}}, reconciler.EnqueueRequestsForQuery(mgr.GetClient(), r.Log, configMapCountsInTheSameNS)).
		Complete(reconciler.New(mgr.GetClient(), r.Log, &sillyv1alpha1.ConfigMapCount{}, r.Reconcile))
}

```

**Comment by imikushin** [comment]
I've also updated the example code to illustrate how to use the logger.

**Comment by rosenhouse** [comment]
Makes sense, thanks!
